### ISSUE TITLE
White background on Tweaks > Startup Applications

### ISSUE THREAD

**Issue by thiagobraga** [EliverLara/Nordic#172]
Hi, Eliver.

I think the title is self explanatory. The Startup Applications screen on Gnome Tweaks app is showing a white background on the list of applications.

![image](https://user-images.githubusercontent.com/993684/141982537-bf870e0b-69f1-48d8-b8fd-215237cc2ec5.png)

I've tried some modifications that worked on GTK+ Inspector, but didn't work when I compile the theme. I've made these changes on `_frames.scss`:

```scss
scrolledwindow {
  viewport.frame { // avoid double borders when viewport inside scrolled window
    border-style: none;

    list.tweak-group-startup row.tweak-startup {
      background-color: $nord0;
    }
  }

  ...
}
```

I'm using these versions:
- Ubuntu 20.04.3
- GNOME Shell 3.36.9

Thanks anyway.
